import { Transaction } from '@/types/transaction'

const vendors = {
  amazon:  { id: "1", name: 'Amazon',      lastTimeUsed: '2024-10-30' },
  whole:   { id: "2", name: 'Whole Foods', lastTimeUsed: '2024-11-01' },
  netflix: { id: "3", name: 'Netflix',     lastTimeUsed: '2024-10-28' },
}

export const SAMPLE_TRANSACTIONS: Transaction[] = [
  {
    id: "1",
    bankAccountId: "4521",
    date: '2024-11-01',
    amountCents: -8499,
    description: 'Amazon order #112-3456789',
    predictedVendorId: vendors.amazon.id,
    actualVendorId: vendors.amazon.id,
    predictedCategory: [{ categoryId: "1", amountCents: 8499 }],
    actualCategory: [{ categoryId: "1", amountCents: 8499 }],
    status: 'Posted',
    needsInfo: false,
  },
  {
    id: "2",
    bankAccountId: "4521",
    date: '2024-11-02',
    amountCents: -5340,
    description: 'Weekly groceries',
    predictedVendorId: vendors.whole.id,
    actualVendorId: vendors.whole.id,
    predictedCategory: [{ categoryId: "2", amountCents: 5340 }],
    actualCategory: [{ categoryId: "2", amountCents: 5340 }],
    status: 'Posted',
    needsInfo: false,
  },
  {
    id: "3",
    bankAccountId: "7890",
    date: '2024-11-03',
    amountCents: -1599,
    description: 'Monthly subscription',
    predictedVendorId: vendors.netflix.id,
    actualVendorId: vendors.netflix.id,
    predictedCategory: [{ categoryId: "3", amountCents: 1599 }],
    actualCategory: [{ categoryId: "3", amountCents: 1599 }],
    status: 'Posted',
    needsInfo: false,
  },
  {
    id: "4",
    bankAccountId: "4521",
    date: '2024-11-04',
    amountCents: -21075,
    description: 'Amazon order #112-9876543',
    predictedVendorId: vendors.amazon.id,
    actualVendorId: vendors.amazon.id,
    predictedCategory: [{ categoryId: "1", amountCents: 21075 }],
    actualCategory: [{ categoryId: "4", amountCents: 21075 }],
    status: 'Pending',
    needsInfo: true,
  },
  {
    id: "5",
    bankAccountId: "4521",
    date: '2024-11-05',
    amountCents: 150000,
    description: 'Direct deposit — payroll',
    predictedVendorId: vendors.amazon.id,
    actualVendorId: vendors.amazon.id,
    predictedCategory: [{ categoryId: "4", amountCents: 150000 }],
    actualCategory: [{ categoryId: "4", amountCents: 150000 }],
    status: 'Posted',
    needsInfo: false,
  },
  {
    id: "6",
    bankAccountId: "7890",
    date: '2024-11-06',
    amountCents: -3210,
    description: 'Grocery run',
    predictedVendorId: vendors.whole.id,
    actualVendorId: vendors.whole.id,
    predictedCategory: [{ categoryId: "2", amountCents: 3210 }],
    actualCategory: [{ categoryId: "2", amountCents: 3210 }],
    status: 'Excluded',
    needsInfo: false,
  },
  {
    id: "7",
    bankAccountId: "7890",
    date: '2024-11-07',
    amountCents: -999,
    description: 'Streaming plan upgrade',
    predictedVendorId: vendors.netflix.id,
    actualVendorId: vendors.netflix.id,
    predictedCategory: [{ categoryId: "3", amountCents: 999 }],
    actualCategory: [{ categoryId: "3", amountCents: 999 }],
    status: 'Pending',
    needsInfo: true,
  },
  {
    id: "8",
    bankAccountId: "4521",
    date: '2024-11-08',
    amountCents: -12750,
    description: 'Amazon order #112-1122334',
    predictedVendorId: vendors.amazon.id,
    actualVendorId: vendors.amazon.id,
    predictedCategory: [{ categoryId: "1", amountCents: 12750 }],
    actualCategory: [{ categoryId: "1", amountCents: 12750 }],
    status: 'Excluded',
    needsInfo: false,
  },
]
