import { Transaction } from '@/types/transaction'

const vendors = {
  amazon:  { id: 1, name: 'Amazon',        lastUsed: new Date('2024-10-30').getTime() },
  whole:   { id: 2, name: 'Whole Foods',   lastUsed: new Date('2024-11-01').getTime() },
  netflix: { id: 3, name: 'Netflix',       lastUsed: new Date('2024-10-28').getTime() },
}

const categories = {
  shopping:      { id: 1, name: 'Shopping' },
  groceries:     { id: 2, name: 'Groceries' },
  entertainment: { id: 3, name: 'Entertainment' },
  utilities:     { id: 4, name: 'Utilities' },
}

export const SAMPLE_TRANSACTIONS: Transaction[] = [
  {
    id: 1,
    date: new Date('2024-11-01').getTime(),
    amount: -84.99,
    description: 'Amazon order #112-3456789',
    from: vendors.amazon,
    predictedCategory: categories.shopping,
    actualCategory: categories.shopping,
    bankAcct: 4521,
    status: 'Posted',
    requireInfo: false,
  },
  {
    id: 2,
    date: new Date('2024-11-02').getTime(),
    amount: -53.40,
    description: 'Weekly groceries',
    from: vendors.whole,
    predictedCategory: categories.groceries,
    actualCategory: categories.groceries,
    bankAcct: 4521,
    status: 'Posted',
    requireInfo: false,
  },
  {
    id: 3,
    date: new Date('2024-11-03').getTime(),
    amount: -15.99,
    description: 'Monthly subscription',
    from: vendors.netflix,
    predictedCategory: categories.entertainment,
    actualCategory: categories.entertainment,
    bankAcct: 7890,
    status: 'Posted',
    requireInfo: false,
  },
  {
    id: 4,
    date: new Date('2024-11-04').getTime(),
    amount: -210.75,
    description: 'Amazon order #112-9876543',
    from: vendors.amazon,
    predictedCategory: categories.shopping,
    actualCategory: categories.utilities,
    bankAcct: 4521,
    status: 'Pending',
    requireInfo: true,
  },
  {
    id: 5,
    date: new Date('2024-11-05').getTime(),
    amount: 1500.00,
    description: 'Direct deposit — payroll',
    from: vendors.amazon,
    predictedCategory: categories.utilities,
    actualCategory: categories.utilities,
    bankAcct: 4521,
    status: 'Posted',
    requireInfo: false,
  },
  {
    id: 6,
    date: new Date('2024-11-06').getTime(),
    amount: -32.10,
    description: 'Grocery run',
    from: vendors.whole,
    predictedCategory: categories.groceries,
    actualCategory: categories.groceries,
    bankAcct: 7890,
    status: 'Excluded',
    requireInfo: false,
  },
  {
    id: 7,
    date: new Date('2024-11-07').getTime(),
    amount: -9.99,
    description: 'Streaming plan upgrade',
    from: vendors.netflix,
    predictedCategory: categories.entertainment,
    actualCategory: categories.entertainment,
    bankAcct: 7890,
    status: 'Pending',
    requireInfo: true,
  },
  {
    id: 8,
    date: new Date('2024-11-08').getTime(),
    amount: -127.50,
    description: 'Amazon order #112-1122334',
    from: vendors.amazon,
    predictedCategory: categories.shopping,
    actualCategory: categories.shopping,
    bankAcct: 4521,
    status: 'Excluded',
    requireInfo: false,
  },
]
